import type { Module } from "@/types";

// Static module registry - used as fallback and for module metadata
// Actual access control is handled by Supabase role_modules table
export const MODULE_REGISTRY: Omit<Module, "id" | "created_at">[] = [
  {
    name: "Sales",
    slug: "sales",
    description: "Sales pipeline, CRM, and revenue tracking",
    icon: "TrendingUp",
    parent_slug: null,
    path: "/m/sales",
    order: 1,
    is_active: true,
  },
  {
    name: "GHL",
    slug: "ghl",
    description: "GoHighLevel integration",
    icon: "Zap",
    parent_slug: "sales",
    path: "/m/sales/ghl",
    order: 1,
    is_active: true,
  },
  {
    name: "Calendar",
    slug: "calendar",
    description: "Appointments and bookings",
    icon: "Calendar",
    parent_slug: "ghl",
    path: "/m/sales/ghl/calendar",
    order: 1,
    is_active: true,
  },
  {
    name: "Opportunities",
    slug: "opportunities",
    description: "Pipeline and deals",
    icon: "Target",
    parent_slug: "ghl",
    path: "/m/sales/ghl/opportunities",
    order: 2,
    is_active: true,
  },
  {
    name: "Sales Pipeline",
    slug: "pipeline",
    description: "Pipeline tracking and management",
    icon: "ClipboardList",
    parent_slug: "sales",
    path: "/m/sales/pipeline",
    order: 2,
    is_active: true,
  },
  {
    name: "Meetings",
    slug: "meetings",
    description: "Meeting management and tracking",
    icon: "Calendar",
    parent_slug: "pipeline",
    path: "/m/sales/pipeline/meetings",
    order: 2,
    is_active: true,
  },
  {
    name: "Maverick",
    slug: "maverick",
    description: "Maverick meeting workspace",
    icon: "Zap",
    parent_slug: "meetings",
    path: "/m/sales/pipeline/meetings/maverick",
    order: 1,
    is_active: true,
  },
  {
    name: "Meet Management",
    slug: "meet-management",
    description: "Maverick's lead and meeting tracking",
    icon: "ClipboardList",
    parent_slug: "maverick",
    path: "/m/sales/pipeline/meetings/maverick/meet-management",
    order: 1,
    is_active: true,
  },
  {
    name: "Sales Management",
    slug: "maverick-sales",
    description: "Won deals tracking and cash collection",
    icon: "DollarSign",
    parent_slug: "maverick",
    path: "/m/sales/pipeline/meetings/maverick/sales-management",
    order: 2,
    is_active: true,
  },
  {
    name: "Analytics",
    slug: "maverick-analytics",
    description: "Meeting and revenue performance analytics",
    icon: "BarChart3",
    parent_slug: "maverick",
    path: "/m/sales/pipeline/meetings/maverick/analytics",
    order: 3,
    is_active: true,
  },
  {
    name: "Calendar",
    slug: "maverick-calendar",
    description: "Maverick's appointment calendar",
    icon: "Calendar",
    parent_slug: "maverick",
    path: "/m/sales/pipeline/meetings/maverick/calendar",
    order: 4,
    is_active: true,
  },
  {
    name: "Jobin",
    slug: "jobin",
    description: "Jobin meeting workspace",
    icon: "Zap",
    parent_slug: "meetings",
    path: "/m/sales/pipeline/meetings/jobin",
    order: 2,
    is_active: true,
  },
  {
    name: "Meet Management",
    slug: "jobin-meet",
    description: "Jobin's lead and meeting tracking",
    icon: "ClipboardList",
    parent_slug: "jobin",
    path: "/m/sales/pipeline/meetings/jobin/meet-management",
    order: 1,
    is_active: true,
  },
  {
    name: "Sales Management",
    slug: "jobin-sales",
    description: "Won deals tracking and cash collection",
    icon: "DollarSign",
    parent_slug: "jobin",
    path: "/m/sales/pipeline/meetings/jobin/sales-management",
    order: 2,
    is_active: true,
  },
  {
    name: "Analytics",
    slug: "jobin-analytics",
    description: "Meeting and revenue performance analytics",
    icon: "BarChart3",
    parent_slug: "jobin",
    path: "/m/sales/pipeline/meetings/jobin/analytics",
    order: 3,
    is_active: true,
  },
  {
    name: "Calendar",
    slug: "jobin-calendar",
    description: "Jobin's appointment calendar",
    icon: "Calendar",
    parent_slug: "jobin",
    path: "/m/sales/pipeline/meetings/jobin/calendar",
    order: 4,
    is_active: true,
  },
  {
    name: "Sales Setting",
    slug: "sales-setting",
    description: "Sales tracking sheets and settings",
    icon: "Settings",
    parent_slug: "pipeline",
    path: "/m/sales/pipeline/settings",
    order: 1,
    is_active: true,
  },
  {
    name: "Onboarding",
    slug: "onboarding",
    description: "Client onboarding and brand assessment",
    icon: "ClipboardList",
    parent_slug: "pipeline",
    path: "/m/sales/pipeline/onboarding",
    order: 3,
    is_active: true,
  },
  {
    name: "Management",
    slug: "onboarding-management",
    description: "Onboarding management and checklist tracking",
    icon: "ClipboardList",
    parent_slug: "onboarding",
    path: "/m/sales/pipeline/onboarding/management",
    order: 1,
    is_active: true,
  },
  {
    name: "Analytics",
    slug: "onboarding-analytics",
    description: "Onboarding performance analytics",
    icon: "BarChart3",
    parent_slug: "onboarding",
    path: "/m/sales/pipeline/onboarding/analytics",
    order: 2,
    is_active: true,
  },
  // ── Payments ─────────────────────────────────────
  {
    name: "Payments",
    slug: "payments",
    description: "Payment tracking, settlements & revenue analytics",
    icon: "CreditCard",
    parent_slug: null,
    path: "/m/payments",
    order: 3,
    is_active: true,
  },
  {
    name: "Dashboard",
    slug: "payments-dashboard",
    description: "Revenue KPIs and payment overview",
    icon: "LayoutDashboard",
    parent_slug: "payments",
    path: "/m/payments/dashboard",
    order: 1,
    is_active: true,
  },
  {
    name: "Transactions",
    slug: "payments-transactions",
    description: "All payment transactions",
    icon: "Receipt",
    parent_slug: "payments",
    path: "/m/payments/transactions",
    order: 2,
    is_active: true,
  },
  {
    name: "Settlements",
    slug: "payments-settlements",
    description: "Settlement cycles and bank transfers",
    icon: "Landmark",
    parent_slug: "payments",
    path: "/m/payments/settlements",
    order: 3,
    is_active: true,
  },
  {
    name: "Invoices",
    slug: "payments-invoices",
    description: "Razorpay invoices and payment links",
    icon: "FileText",
    parent_slug: "payments",
    path: "/m/payments/invoices",
    order: 4,
    is_active: true,
  },
  {
    name: "Payment Pages",
    slug: "payments-pages",
    description: "Razorpay payment pages and collection links",
    icon: "ScrollText",
    parent_slug: "payments",
    path: "/m/payments/payment-pages",
    order: 5,
    is_active: true,
  },
  {
    name: "Analytics",
    slug: "payments-analytics",
    description: "Deep payment analytics and trends",
    icon: "PieChart",
    parent_slug: "payments",
    path: "/m/payments/analytics",
    order: 6,
    is_active: true,
  },
  // ── Marketing ─────────────────────────────────────
  {
    name: "Marketing",
    slug: "marketing",
    description: "Ad campaigns, analytics, and marketing tools",
    icon: "Megaphone",
    parent_slug: null,
    path: "/m/marketing",
    order: 2,
    is_active: true,
  },
  {
    name: "Meta",
    slug: "meta",
    description: "Facebook & Instagram Ads",
    icon: "Share2",
    parent_slug: "marketing",
    path: "/m/marketing/meta",
    order: 1,
    is_active: true,
  },
  {
    name: "Campaigns",
    slug: "meta-campaigns",
    description: "Ad campaigns overview",
    icon: "BarChart3",
    parent_slug: "meta",
    path: "/m/marketing/meta/campaigns",
    order: 1,
    is_active: true,
  },
  {
    name: "Ad Sets",
    slug: "meta-adsets",
    description: "Ad set management",
    icon: "Layers",
    parent_slug: "meta",
    path: "/m/marketing/meta/adsets",
    order: 2,
    is_active: true,
  },
  {
    name: "Ads",
    slug: "meta-ads",
    description: "Individual ads",
    icon: "Image",
    parent_slug: "meta",
    path: "/m/marketing/meta/ads",
    order: 3,
    is_active: true,
  },
  {
    name: "Analytics",
    slug: "meta-analytics",
    description: "Demographic & breakdown analytics",
    icon: "PieChart",
    parent_slug: "meta",
    path: "/m/marketing/meta/analytics",
    order: 4,
    is_active: true,
  },
  // ── SEO ───────────────────────────────────────────
  {
    name: "SEO",
    slug: "seo",
    description: "Search Console, keywords & Google Business Profile",
    icon: "Search",
    parent_slug: "marketing",
    path: "/m/marketing/seo",
    order: 2,
    is_active: true,
  },
  {
    name: "Dashboard",
    slug: "seo-dashboard",
    description: "SEO overview and KPIs",
    icon: "LayoutDashboard",
    parent_slug: "seo",
    path: "/m/marketing/seo",
    order: 1,
    is_active: true,
  },
  {
    name: "Search Performance",
    slug: "seo-performance",
    description: "GSC queries, pages, countries, devices",
    icon: "TrendingUp",
    parent_slug: "seo",
    path: "/m/marketing/seo/performance",
    order: 2,
    is_active: true,
  },
  {
    name: "Pages & Indexing",
    slug: "seo-indexing",
    description: "URL inspection, coverage, crawl stats",
    icon: "FileSearch",
    parent_slug: "seo",
    path: "/m/marketing/seo/indexing",
    order: 3,
    is_active: true,
  },
  {
    name: "Keywords",
    slug: "seo-keywords",
    description: "Keyword tracking and opportunities",
    icon: "Tag",
    parent_slug: "seo",
    path: "/m/marketing/seo/keywords",
    order: 4,
    is_active: true,
  },
  {
    name: "Sitemap",
    slug: "seo-sitemap",
    description: "Sitemap status and URL indexing",
    icon: "MapIcon",
    parent_slug: "seo",
    path: "/m/marketing/seo/sitemap",
    order: 5,
    is_active: true,
  },
  {
    name: "Google Business",
    slug: "seo-gbp",
    description: "Google Business Profile insights",
    icon: "MapPin",
    parent_slug: "seo",
    path: "/m/marketing/seo/business",
    order: 6,
    is_active: true,
  },
  // ── Content ─────────────────────────────────────────
  {
    name: "Content",
    slug: "content",
    description: "Ad creatives, social media, and video editing",
    icon: "FileText",
    parent_slug: "marketing",
    path: "/m/marketing/content",
    order: 3,
    is_active: true,
  },
  {
    name: "Ads",
    slug: "content-ads",
    description: "Ad scripts and graphic briefs",
    icon: "PenTool",
    parent_slug: "content",
    path: "/m/marketing/content/ads",
    order: 1,
    is_active: true,
  },
  {
    name: "Social Media",
    slug: "content-social",
    description: "Social media content management",
    icon: "Share2",
    parent_slug: "content",
    path: "/m/marketing/content/social",
    order: 2,
    is_active: true,
  },
  {
    name: "LinkedIn",
    slug: "content-linkedin",
    description: "LinkedIn content management",
    icon: "Linkedin",
    parent_slug: "content-social",
    path: "/m/marketing/content/social/linkedin",
    order: 1,
    is_active: true,
  },
  {
    name: "Instagram",
    slug: "content-instagram",
    description: "Instagram content management",
    icon: "Instagram",
    parent_slug: "content-social",
    path: "/m/marketing/content/social/instagram",
    order: 2,
    is_active: true,
  },
  {
    name: "YouTube",
    slug: "content-youtube",
    description: "YouTube content management",
    icon: "Youtube",
    parent_slug: "content-social",
    path: "/m/marketing/content/social/youtube",
    order: 3,
    is_active: true,
  },
  {
    name: "Video Editing",
    slug: "content-video",
    description: "Video editing pipeline management",
    icon: "Film",
    parent_slug: "content",
    path: "/m/marketing/content/video-editing",
    order: 3,
    is_active: true,
  },
  // ── Analytics ────────────────────────────────────────
  {
    name: "Analytics",
    slug: "analytics",
    description: "Centralized company analytics and campaign tracking",
    icon: "BarChart3",
    parent_slug: null,
    path: "/m/analytics",
    order: 4,
    is_active: true,
  },
  {
    name: "Overview",
    slug: "analytics-overview",
    description: "Aggregated KPIs across all departments",
    icon: "LayoutDashboard",
    parent_slug: "analytics",
    path: "/m/analytics/overview",
    order: 1,
    is_active: true,
  },
  {
    name: "Meta Ads",
    slug: "analytics-meta",
    description: "Meta ad spend, reach, and ROAS analytics",
    icon: "Share2",
    parent_slug: "analytics",
    path: "/m/analytics/meta-ads",
    order: 2,
    is_active: true,
  },
  {
    name: "SEO",
    slug: "analytics-seo",
    description: "Search Console performance and rankings",
    icon: "Search",
    parent_slug: "analytics",
    path: "/m/analytics/seo",
    order: 3,
    is_active: true,
  },
  {
    name: "Payments",
    slug: "analytics-payments",
    description: "Revenue, transactions, and payment trends",
    icon: "CreditCard",
    parent_slug: "analytics",
    path: "/m/analytics/payments",
    order: 4,
    is_active: true,
  },
  {
    name: "Sales",
    slug: "analytics-sales",
    description: "Sales pipeline and conversion analytics",
    icon: "TrendingUp",
    parent_slug: "analytics",
    path: "/m/analytics/sales",
    order: 5,
    is_active: true,
  },
  {
    name: "GHL Dashboard",
    slug: "analytics-ghl",
    description: "GoHighLevel pipeline and opportunity analytics",
    icon: "Zap",
    parent_slug: "analytics",
    path: "/m/analytics/ghl",
    order: 6,
    is_active: true,
  },
  {
    name: "Cohort Tracker",
    slug: "analytics-cohort",
    description: "Admissions cohort funnel and automated daily KPI tracking",
    icon: "Target",
    parent_slug: "analytics",
    path: "/m/analytics/cohort-tracker",
    order: 7,
    is_active: true,
  },
  // ── Admin ─────────────────────────────────────────
  {
    name: "Admin",
    slug: "admin",
    description: "User management, roles & permissions",
    icon: "Shield",
    parent_slug: null,
    path: "/m/admin",
    order: 99,
    is_active: true,
  },
  {
    name: "People",
    slug: "admin-people",
    description: "Manage users and invitations",
    icon: "Users",
    parent_slug: "admin",
    path: "/m/admin/people",
    order: 1,
    is_active: true,
  },
  {
    name: "Roles",
    slug: "admin-roles",
    description: "Role definitions and management",
    icon: "Key",
    parent_slug: "admin",
    path: "/m/admin/roles",
    order: 2,
    is_active: true,
  },
  {
    name: "Permissions",
    slug: "admin-permissions",
    description: "Role-module access and user overrides",
    icon: "Shield",
    parent_slug: "admin",
    path: "/m/admin/permissions",
    order: 3,
    is_active: true,
  },
  {
    name: "Audit Log",
    slug: "admin-audit",
    description: "Activity logs and audit trail",
    icon: "ScrollText",
    parent_slug: "admin",
    path: "/m/admin/audit-log",
    order: 4,
    is_active: true,
  },
];

// Map icon names to actual Lucide icon components (used in components)
export const ICON_MAP: Record<string, string> = {
  TrendingUp: "TrendingUp",
  Zap: "Zap",
  Calendar: "Calendar",
  Target: "Target",
  Users: "Users",
  BookOpen: "BookOpen",
  DollarSign: "DollarSign",
  BarChart3: "BarChart3",
  Settings: "Settings",
  ClipboardList: "ClipboardList",
  MessageSquare: "MessageSquare",
  Package: "Package",
  Megaphone: "Megaphone",
  Share2: "Share2",
  Layers: "Layers",
  Image: "Image",
  PieChart: "PieChart",
  Search: "Search",
  FileSearch: "FileSearch",
  Tag: "Tag",
  MapIcon: "MapIcon",
  MapPin: "MapPin",
  LayoutDashboard: "LayoutDashboard",
  FileText: "FileText",
  PenTool: "PenTool",
  Film: "Film",
  Linkedin: "Linkedin",
  Instagram: "Instagram",
  Youtube: "Youtube",
  CreditCard: "CreditCard",
  Receipt: "Receipt",
  Landmark: "Landmark",
  ScrollText: "ScrollText",
  Shield: "Shield",
  Key: "Key",
};

export function getModuleBySlug(slug: string) {
  return MODULE_REGISTRY.find((m) => m.slug === slug);
}

export function getChildrenByParentSlug(parentSlug: string) {
  return MODULE_REGISTRY.filter((m) => m.parent_slug === parentSlug).sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
}

export function buildBreadcrumbFromPath(pathSegments: string[]) {
  const breadcrumbs = [{ label: "APEX OS", href: "/" }];

  let currentPath = "/m";
  for (const segment of pathSegments) {
    currentPath += `/${segment}`;
    const mod = MODULE_REGISTRY.find((m) => m.path === currentPath);
    breadcrumbs.push({
      label: mod?.name || segment,
      href: currentPath,
    });
  }

  return breadcrumbs;
}
