import type { Module } from "@/types";

// Static module registry - used as fallback and for module metadata
// Actual access control is handled by Supabase role_modules table
export const MODULE_REGISTRY: Omit<Module, "id" | "created_at">[] = [
  {
    name: "Sales",
    slug: "sales",
    description: "Sales pipeline, CRM, and revenue tracking",
    icon: "TrendingUp",
    parent_slug: null,
    path: "/m/sales",
    order: 1,
    is_active: true,
  },
  {
    name: "GHL",
    slug: "ghl",
    description: "GoHighLevel integration",
    icon: "Zap",
    parent_slug: "sales",
    path: "/m/sales/ghl",
    order: 1,
    is_active: true,
  },
  {
    name: "Calendar",
    slug: "calendar",
    description: "Appointments and bookings",
    icon: "Calendar",
    parent_slug: "ghl",
    path: "/m/sales/ghl/calendar",
    order: 1,
    is_active: true,
  },
  {
    name: "Opportunities",
    slug: "opportunities",
    description: "Pipeline and deals",
    icon: "Target",
    parent_slug: "ghl",
    path: "/m/sales/ghl/opportunities",
    order: 2,
    is_active: true,
  },
  {
    name: "Sales Pipeline",
    slug: "pipeline",
    description: "Pipeline tracking and management",
    icon: "ClipboardList",
    parent_slug: "sales",
    path: "/m/sales/pipeline",
    order: 2,
    is_active: true,
  },
  {
    name: "Meetings",
    slug: "meetings",
    description: "Meeting management and tracking",
    icon: "Calendar",
    parent_slug: "pipeline",
    path: "/m/sales/pipeline/meetings",
    order: 2,
    is_active: true,
  },
  {
    name: "Sales Reps",
    slug: "sales-reps",
    description: "Sales rep management",
    icon: "Users",
    parent_slug: "meetings",
    path: "/m/sales/pipeline/meetings/sales-reps",
    order: 1,
    is_active: true,
  },
  {
    name: "Meet Management",
    slug: "rep-meet-management",
    description: "Sales rep meeting management",
    icon: "CalendarCheck",
    parent_slug: "sales-reps",
    path: "/m/sales/pipeline/meetings/sales-reps/meet-management",
    order: 1,
    is_active: true,
  },
  {
    name: "Sales Management",
    slug: "rep-sales-management",
    description: "Sales rep deal tracking",
    icon: "DollarSign",
    parent_slug: "sales-reps",
    path: "/m/sales/pipeline/meetings/sales-reps/sales-management",
    order: 2,
    is_active: true,
  },
  {
    name: "Analytics",
    slug: "rep-analytics",
    description: "Sales rep performance analytics",
    icon: "BarChart3",
    parent_slug: "sales-reps",
    path: "/m/sales/pipeline/meetings/sales-reps/analytics",
    order: 3,
    is_active: true,
  },
  {
    name: "Calendar",
    slug: "rep-calendar",
    description: "Sales rep calendar",
    icon: "Calendar",
    parent_slug: "sales-reps",
    path: "/m/sales/pipeline/meetings/sales-reps/calendar",
    order: 4,
    is_active: true,
  },
  {
    name: "Meeting Sheet",
    slug: "rep-meeting-sheet",
    description: "Sales rep meeting analysis sheet",
    icon: "Sheet",
    parent_slug: "sales-reps",
    path: "/m/sales/pipeline/meetings/sales-reps/meeting-sheet",
    order: 5,
    is_active: true,
  },
  {
    name: "Sales Setting",
    slug: "sales-setting",
    description: "Sales tracking sheets and settings",
    icon: "Settings",
    parent_slug: "pipeline",
    path: "/m/sales/pipeline/settings",
    order: 1,
    is_active: true,
  },
  {
    name: "Onboarding",
    slug: "onboarding",
    description: "Client onboarding and brand assessment",
    icon: "ClipboardList",
    parent_slug: "pipeline",
    path: "/m/sales/pipeline/onboarding",
    order: 3,
    is_active: true,
  },
  {
    name: "Management",
    slug: "onboarding-management",
    description: "Onboarding management and checklist tracking",
    icon: "ClipboardList",
    parent_slug: "onboarding",
    path: "/m/sales/pipeline/onboarding/management",
    order: 1,
    is_active: true,
  },
  {
    name: "Analytics",
    slug: "onboarding-analytics",
    description: "Onboarding performance analytics",
    icon: "BarChart3",
    parent_slug: "onboarding",
    path: "/m/sales/pipeline/onboarding/analytics",
    order: 2,
    is_active: true,
  },
  // ── Payments ─────────────────────────────────────
  {
    name: "Payments",
    slug: "payments",
    description: "Payment tracking, settlements & revenue analytics",
    icon: "CreditCard",
    parent_slug: null,
    path: "/m/payments",
    order: 3,
    is_active: true,
  },
  {
    name: "Dashboard",
    slug: "payments-dashboard",
    description: "Revenue KPIs and payment overview",
    icon: "LayoutDashboard",
    parent_slug: "payments",
    path: "/m/payments/dashboard",
    order: 1,
    is_active: true,
  },
  {
    name: "Transactions",
    slug: "payments-transactions",
    description: "All payment transactions",
    icon: "Receipt",
    parent_slug: "payments",
    path: "/m/payments/transactions",
    order: 2,
    is_active: true,
  },
  {
    name: "Settlements",
    slug: "payments-settlements",
    description: "Settlement cycles and bank transfers",
    icon: "Landmark",
    parent_slug: "payments",
    path: "/m/payments/settlements",
    order: 3,
    is_active: true,
  },
  {
    name: "Invoices",
    slug: "payments-invoices",
    description: "Razorpay invoices and payment links",
    icon: "FileText",
    parent_slug: "payments",
    path: "/m/payments/invoices",
    order: 4,
    is_active: true,
  },
  {
    name: "Payment Pages",
    slug: "payments-pages",
    description: "Razorpay payment pages and collection links",
    icon: "ScrollText",
    parent_slug: "payments",
    path: "/m/payments/payment-pages",
    order: 5,
    is_active: true,
  },
  {
    name: "Analytics",
    slug: "payments-analytics",
    description: "Deep payment analytics and trends",
    icon: "PieChart",
    parent_slug: "payments",
    path: "/m/payments/analytics",
    order: 6,
    is_active: true,
  },
  {
    name: "Failed Payments",
    slug: "payments-failed",
    description: "Track and follow up on failed payments",
    icon: "AlertTriangle",
    parent_slug: "payments",
    path: "/m/payments/failed-payments",
    order: 7,
    is_active: true,
  },
  {
    name: "Send Links",
    slug: "payments-send-links",
    description: "Quick-send payment links to customers",
    icon: "Send",
    parent_slug: "payments",
    path: "/m/payments/send-links",
    order: 8,
    is_active: true,
  },
  {
    name: "Collection Log",
    slug: "payments-collection-log",
    description: "Daily collection reconciliation sheet",
    icon: "ClipboardList",
    parent_slug: "payments",
    path: "/m/payments/collection-log",
    order: 9,
    is_active: true,
  },
  {
    name: "Outstanding",
    slug: "payments-outstanding",
    description: "Outstanding and overdue invoices follow-up",
    icon: "AlertCircle",
    parent_slug: "payments",
    path: "/m/payments/outstanding",
    order: 10,
    is_active: true,
  },
  // ── Marketing ─────────────────────────────────────
  {
    name: "Marketing",
    slug: "marketing",
    description: "Ad campaigns, analytics, and marketing tools",
    icon: "Megaphone",
    parent_slug: null,
    path: "/m/marketing",
    order: 2,
    is_active: true,
  },
  {
    name: "Meta",
    slug: "meta",
    description: "Facebook & Instagram Ads",
    icon: "Share2",
    parent_slug: "marketing",
    path: "/m/marketing/meta",
    order: 1,
    is_active: true,
  },
  {
    name: "Campaigns",
    slug: "meta-campaigns",
    description: "Ad campaigns overview",
    icon: "BarChart3",
    parent_slug: "meta",
    path: "/m/marketing/meta/campaigns",
    order: 1,
    is_active: true,
  },
  {
    name: "Ad Sets",
    slug: "meta-adsets",
    description: "Ad set management",
    icon: "Layers",
    parent_slug: "meta",
    path: "/m/marketing/meta/adsets",
    order: 2,
    is_active: true,
  },
  {
    name: "Ads",
    slug: "meta-ads",
    description: "Individual ads",
    icon: "Image",
    parent_slug: "meta",
    path: "/m/marketing/meta/ads",
    order: 3,
    is_active: true,
  },
  {
    name: "Analytics",
    slug: "meta-analytics",
    description: "Demographic & breakdown analytics",
    icon: "PieChart",
    parent_slug: "meta",
    path: "/m/marketing/meta/analytics",
    order: 4,
    is_active: true,
  },
  {
    name: "Campaign Tracker",
    slug: "meta-campaign-tracker",
    description: "Daily campaign decision log",
    icon: "ClipboardList",
    parent_slug: "meta",
    path: "/m/marketing/meta/campaign-tracker",
    order: 5,
    is_active: true,
  },
  {
    name: "Creative Tracker",
    slug: "meta-creative-tracker",
    description: "Creative fatigue monitoring",
    icon: "Palette",
    parent_slug: "meta",
    path: "/m/marketing/meta/creative-tracker",
    order: 6,
    is_active: true,
  },
  {
    name: "Budget Planner",
    slug: "meta-budget-planner",
    description: "Planned vs actual budget tracking",
    icon: "Wallet",
    parent_slug: "meta",
    path: "/m/marketing/meta/budget-planner",
    order: 7,
    is_active: true,
  },
  {
    name: "Conversion Log",
    slug: "meta-conversion-log",
    description: "Lead quality and conversion tracking",
    icon: "UserCheck",
    parent_slug: "meta",
    path: "/m/marketing/meta/conversion-log",
    order: 8,
    is_active: true,
  },
  {
    name: "Creative Analysis",
    slug: "meta-creative-analysis",
    description: "Creative performance ranking and comparison",
    icon: "BarChart3",
    parent_slug: "meta",
    path: "/m/marketing/meta/creative-analysis",
    order: 9,
    is_active: true,
  },
  {
    name: "Audience Insights",
    slug: "meta-audience-insights",
    description: "Cross-dimensional audience analysis",
    icon: "Users",
    parent_slug: "meta",
    path: "/m/marketing/meta/audience-insights",
    order: 10,
    is_active: true,
  },
  // ── SEO ───────────────────────────────────────────
  {
    name: "SEO",
    slug: "seo",
    description: "Search Console, keywords & Google Business Profile",
    icon: "Search",
    parent_slug: "marketing",
    path: "/m/marketing/seo",
    order: 2,
    is_active: true,
  },
  {
    name: "Dashboard",
    slug: "seo-dashboard",
    description: "SEO overview and KPIs",
    icon: "LayoutDashboard",
    parent_slug: "seo",
    path: "/m/marketing/seo",
    order: 1,
    is_active: true,
  },
  {
    name: "Search Performance",
    slug: "seo-performance",
    description: "GSC queries, pages, countries, devices",
    icon: "TrendingUp",
    parent_slug: "seo",
    path: "/m/marketing/seo/performance",
    order: 2,
    is_active: true,
  },
  {
    name: "Pages & Indexing",
    slug: "seo-indexing",
    description: "URL inspection, coverage, crawl stats",
    icon: "FileSearch",
    parent_slug: "seo",
    path: "/m/marketing/seo/indexing",
    order: 3,
    is_active: true,
  },
  {
    name: "Keywords",
    slug: "seo-keywords",
    description: "Keyword tracking and opportunities",
    icon: "Tag",
    parent_slug: "seo",
    path: "/m/marketing/seo/keywords",
    order: 4,
    is_active: true,
  },
  {
    name: "Sitemap",
    slug: "seo-sitemap",
    description: "Sitemap status and URL indexing",
    icon: "MapIcon",
    parent_slug: "seo",
    path: "/m/marketing/seo/sitemap",
    order: 5,
    is_active: true,
  },
  {
    name: "Google Business",
    slug: "seo-gbp",
    description: "Google Business Profile insights",
    icon: "MapPin",
    parent_slug: "seo",
    path: "/m/marketing/seo/business",
    order: 6,
    is_active: true,
  },
  {
    name: "Keyword Tracker",
    slug: "seo-keyword-tracker",
    description: "Track target keywords with position goals",
    icon: "Crosshair",
    parent_slug: "seo",
    path: "/m/marketing/seo/keyword-tracker",
    order: 7,
    is_active: true,
  },
  {
    name: "Task Log",
    slug: "seo-task-log",
    description: "SEO and content task management",
    icon: "CheckSquare",
    parent_slug: "seo",
    path: "/m/marketing/seo/task-log",
    order: 8,
    is_active: true,
  },
  {
    name: "Competitor Tracker",
    slug: "seo-competitor-tracker",
    description: "Monitor competitor keyword rankings",
    icon: "Swords",
    parent_slug: "seo",
    path: "/m/marketing/seo/competitor-tracker",
    order: 9,
    is_active: true,
  },
  {
    name: "Content Briefs",
    slug: "seo-content-briefs",
    description: "Content brief creation and tracking",
    icon: "FileEdit",
    parent_slug: "seo",
    path: "/m/marketing/seo/content-briefs",
    order: 10,
    is_active: true,
  },
  {
    name: "Rank Analysis",
    slug: "seo-rank-analysis",
    description: "Ranking performance analysis and quick wins",
    icon: "LineChart",
    parent_slug: "seo",
    path: "/m/marketing/seo/rank-analysis",
    order: 11,
    is_active: true,
  },
  {
    name: "Page Health",
    slug: "seo-page-health",
    description: "Page-level health monitoring and scores",
    icon: "HeartPulse",
    parent_slug: "seo",
    path: "/m/marketing/seo/page-health",
    order: 12,
    is_active: true,
  },
  // ── Content ─────────────────────────────────────────
  {
    name: "Content",
    slug: "content",
    description: "Ad creatives, social media, and video editing",
    icon: "FileText",
    parent_slug: "marketing",
    path: "/m/marketing/content",
    order: 3,
    is_active: true,
  },
  {
    name: "Ads",
    slug: "content-ads",
    description: "Ad scripts and graphic briefs",
    icon: "PenTool",
    parent_slug: "content",
    path: "/m/marketing/content/ads",
    order: 1,
    is_active: true,
  },
  {
    name: "Social Media",
    slug: "content-social",
    description: "Social media content management",
    icon: "Share2",
    parent_slug: "content",
    path: "/m/marketing/content/social",
    order: 2,
    is_active: true,
  },
  {
    name: "SOP Tracker",
    slug: "content-sop-tracker",
    description: "Daily content publishing SOP checklist",
    icon: "CheckSquare",
    parent_slug: "content-social",
    path: "/m/marketing/content/social/sop-tracker",
    order: 0,
    is_active: true,
  },
  {
    name: "LinkedIn",
    slug: "content-linkedin",
    description: "LinkedIn content management",
    icon: "Linkedin",
    parent_slug: "content-social",
    path: "/m/marketing/content/social/linkedin",
    order: 1,
    is_active: true,
  },
  {
    name: "Instagram",
    slug: "content-instagram",
    description: "Instagram content management",
    icon: "Instagram",
    parent_slug: "content-social",
    path: "/m/marketing/content/social/instagram",
    order: 2,
    is_active: true,
  },
  {
    name: "YouTube",
    slug: "content-youtube",
    description: "YouTube content management",
    icon: "Youtube",
    parent_slug: "content-social",
    path: "/m/marketing/content/social/youtube",
    order: 3,
    is_active: true,
  },
  {
    name: "Video Editing",
    slug: "content-video",
    description: "Video editing pipeline management",
    icon: "Film",
    parent_slug: "content",
    path: "/m/marketing/content/video-editing",
    order: 3,
    is_active: true,
  },
  // ── Analytics ────────────────────────────────────────
  {
    name: "Analytics",
    slug: "analytics",
    description: "Centralized company analytics and campaign tracking",
    icon: "BarChart3",
    parent_slug: null,
    path: "/m/analytics",
    order: 4,
    is_active: true,
  },
  {
    name: "Overview",
    slug: "analytics-overview",
    description: "Aggregated KPIs across all departments",
    icon: "LayoutDashboard",
    parent_slug: "analytics",
    path: "/m/analytics/overview",
    order: 1,
    is_active: true,
  },
  {
    name: "Meta Ads",
    slug: "analytics-meta",
    description: "Meta ad spend, reach, and ROAS analytics",
    icon: "Share2",
    parent_slug: "analytics",
    path: "/m/analytics/meta-ads",
    order: 2,
    is_active: true,
  },
  {
    name: "SEO",
    slug: "analytics-seo",
    description: "Search Console performance and rankings",
    icon: "Search",
    parent_slug: "analytics",
    path: "/m/analytics/seo",
    order: 3,
    is_active: true,
  },
  {
    name: "Payments",
    slug: "analytics-payments",
    description: "Revenue, transactions, and payment trends",
    icon: "CreditCard",
    parent_slug: "analytics",
    path: "/m/analytics/payments",
    order: 4,
    is_active: true,
  },
  {
    name: "Sales",
    slug: "analytics-sales",
    description: "Sales pipeline and conversion analytics",
    icon: "TrendingUp",
    parent_slug: "analytics",
    path: "/m/analytics/sales",
    order: 5,
    is_active: true,
  },
  {
    name: "GHL Dashboard",
    slug: "analytics-ghl",
    description: "GoHighLevel pipeline and opportunity analytics",
    icon: "Zap",
    parent_slug: "analytics",
    path: "/m/analytics/ghl",
    order: 6,
    is_active: true,
  },
  {
    name: "Cohort Tracker",
    slug: "analytics-cohort",
    description: "Admissions cohort funnel and automated daily KPI tracking",
    icon: "Target",
    parent_slug: "analytics",
    path: "/m/analytics/cohort-tracker",
    order: 7,
    is_active: true,
  },
  {
    name: "Daily Sheet",
    slug: "analytics-daily-sheet",
    description: "Daily campaign spend, meetings, and conversion tracking",
    icon: "ClipboardList",
    parent_slug: "analytics",
    path: "/m/analytics/daily-sheet",
    order: 8,
    is_active: true,
  },
  // ── HR ──────────────────────────────────────────────
  {
    name: "HR",
    slug: "hr",
    description: "Employee profiles, KPIs, salary & payroll",
    icon: "Briefcase",
    parent_slug: null,
    path: "/m/hr",
    order: 5,
    is_active: true,
  },
  {
    name: "Dashboard",
    slug: "hr-dashboard",
    description: "HR overview and headcount stats",
    icon: "LayoutDashboard",
    parent_slug: "hr",
    path: "/m/hr/dashboard",
    order: 1,
    is_active: true,
  },
  {
    name: "Employees",
    slug: "hr-employees",
    description: "Employee directory and profiles",
    icon: "Users",
    parent_slug: "hr",
    path: "/m/hr/employees",
    order: 2,
    is_active: true,
  },
  {
    name: "Departments",
    slug: "hr-departments",
    description: "Department management",
    icon: "Building2",
    parent_slug: "hr",
    path: "/m/hr/departments",
    order: 3,
    is_active: true,
  },
  {
    name: "Designations",
    slug: "hr-designations",
    description: "Job titles and levels",
    icon: "BadgeCheck",
    parent_slug: "hr",
    path: "/m/hr/designations",
    order: 4,
    is_active: true,
  },
  {
    name: "KPIs & KRAs",
    slug: "hr-kpis",
    description: "Performance indicators and result areas",
    icon: "Target",
    parent_slug: "hr",
    path: "/m/hr/kpis",
    order: 5,
    is_active: true,
  },
  {
    name: "Salary",
    slug: "hr-salary",
    description: "Salary records and commission rules",
    icon: "IndianRupee",
    parent_slug: "hr",
    path: "/m/hr/salary",
    order: 6,
    is_active: true,
  },
  {
    name: "Payroll Tracker",
    slug: "hr-payroll",
    description: "Monthly payroll cycle tracking",
    icon: "Wallet",
    parent_slug: "hr",
    path: "/m/hr/payroll",
    order: 7,
    is_active: true,
  },
  {
    name: "Settings",
    slug: "hr-settings",
    description: "HR configuration, user-employee linking, and designation-role mapping",
    icon: "Settings",
    parent_slug: "hr",
    path: "/m/hr/settings",
    order: 8,
    is_active: true,
  },
  {
    name: "Leaves",
    slug: "hr-leaves",
    description: "Leave requests and approval workflow",
    icon: "CalendarOff",
    parent_slug: "hr",
    path: "/m/hr/leaves",
    order: 9,
    is_active: true,
  },
  {
    name: "Holidays",
    slug: "hr-holidays",
    description: "Company holiday calendar",
    icon: "PartyPopper",
    parent_slug: "hr",
    path: "/m/hr/holidays",
    order: 10,
    is_active: true,
  },
  // ── Tasks & Projects ────────────────────────────────
  {
    name: "Tasks",
    slug: "tasks",
    description: "Task management, projects & kanban board",
    icon: "ClipboardList",
    parent_slug: null,
    path: "/m/tasks",
    order: 6,
    is_active: true,
  },
  {
    name: "Board",
    slug: "tasks-board",
    description: "Kanban board view for tasks",
    icon: "LayoutDashboard",
    parent_slug: "tasks",
    path: "/m/tasks/board",
    order: 1,
    is_active: true,
  },
  {
    name: "My Tasks",
    slug: "tasks-my",
    description: "Tasks assigned to me",
    icon: "CheckSquare",
    parent_slug: "tasks",
    path: "/m/tasks/my",
    order: 2,
    is_active: true,
  },
  {
    name: "Team Tasks",
    slug: "tasks-team",
    description: "Tasks across the team",
    icon: "Users",
    parent_slug: "tasks",
    path: "/m/tasks/team",
    order: 3,
    is_active: true,
  },
  {
    name: "Projects",
    slug: "tasks-projects",
    description: "Project management and overview",
    icon: "FolderOpen",
    parent_slug: "tasks",
    path: "/m/tasks/projects",
    order: 4,
    is_active: true,
  },
  // ── Finance & Expenses ─────────────────────────────
  {
    name: "Finance",
    slug: "finance",
    description: "Expenses, budgets, and financial tracking",
    icon: "Landmark",
    parent_slug: null,
    path: "/m/finance",
    order: 7,
    is_active: true,
  },
  {
    name: "Expenses",
    slug: "finance-expenses",
    description: "Expense log and tracking",
    icon: "Receipt",
    parent_slug: "finance",
    path: "/m/finance/expenses",
    order: 1,
    is_active: true,
  },
  {
    name: "Budgets",
    slug: "finance-budgets",
    description: "Budget planning and tracking",
    icon: "Wallet",
    parent_slug: "finance",
    path: "/m/finance/budgets",
    order: 2,
    is_active: true,
  },
  {
    name: "Categories",
    slug: "finance-categories",
    description: "Expense category management",
    icon: "FolderOpen",
    parent_slug: "finance",
    path: "/m/finance/categories",
    order: 3,
    is_active: true,
  },
  // ── Internal Chat ──────────────────────────────────
  {
    name: "Chat",
    slug: "chat",
    description: "Internal team messaging and channels",
    icon: "MessageSquare",
    parent_slug: null,
    path: "/m/chat",
    order: 8,
    is_active: true,
  },
  // ── Automations ─────────────────────────────────────
  {
    name: "Automations",
    slug: "automations",
    description: "Email automations and workflows",
    icon: "Zap",
    parent_slug: null,
    path: "/m/automations",
    order: 9,
    is_active: true,
  },
  {
    name: "Email",
    slug: "automations-email",
    description: "Invoice emails and templates",
    icon: "Mail",
    parent_slug: "automations",
    path: "/m/automations/email",
    order: 1,
    is_active: true,
  },
  {
    name: "Templates",
    slug: "automations-email-templates",
    description: "Create and edit email templates",
    icon: "FileText",
    parent_slug: "automations-email",
    path: "/m/automations/email/templates",
    order: 1,
    is_active: true,
  },
  {
    name: "Compose",
    slug: "automations-email-compose",
    description: "Compose and send invoice emails",
    icon: "PenTool",
    parent_slug: "automations-email",
    path: "/m/automations/email/compose",
    order: 2,
    is_active: true,
  },
  // ── Admin ─────────────────────────────────────────
  {
    name: "Admin",
    slug: "admin",
    description: "User management, roles & permissions",
    icon: "Shield",
    parent_slug: null,
    path: "/m/admin",
    order: 99,
    is_active: true,
  },
  {
    name: "People",
    slug: "admin-people",
    description: "Manage users and invitations",
    icon: "Users",
    parent_slug: "admin",
    path: "/m/admin/people",
    order: 1,
    is_active: true,
  },
  {
    name: "Roles",
    slug: "admin-roles",
    description: "Role definitions and management",
    icon: "Key",
    parent_slug: "admin",
    path: "/m/admin/roles",
    order: 2,
    is_active: true,
  },
  {
    name: "Permissions",
    slug: "admin-permissions",
    description: "Role-module access and user overrides",
    icon: "Shield",
    parent_slug: "admin",
    path: "/m/admin/permissions",
    order: 3,
    is_active: true,
  },
  {
    name: "Audit Log",
    slug: "admin-audit",
    description: "Activity logs and audit trail",
    icon: "ScrollText",
    parent_slug: "admin",
    path: "/m/admin/audit-log",
    order: 4,
    is_active: true,
  },
  // ── Guides Module ──────────────────────────
  {
    name: "Guides",
    slug: "guides",
    description: "Help docs, user guides & API reference",
    icon: "BookOpen",
    parent_slug: null,
    path: "/m/guides",
    order: 11,
    is_active: true,
  },
  {
    name: "Chat Guide",
    slug: "guides-chat",
    description: "How to use the messaging system",
    icon: "MessageCircle",
    parent_slug: "guides",
    path: "/m/guides/chat",
    order: 1,
    is_active: true,
  },
  {
    name: "API Reference",
    slug: "guides-api",
    description: "API documentation for developers",
    icon: "Code",
    parent_slug: "guides",
    path: "/m/guides/api",
    order: 2,
    is_active: true,
  },
];

// Map icon names to actual Lucide icon components (used in components)
export const ICON_MAP: Record<string, string> = {
  TrendingUp: "TrendingUp",
  Zap: "Zap",
  Calendar: "Calendar",
  Target: "Target",
  Users: "Users",
  BookOpen: "BookOpen",
  DollarSign: "DollarSign",
  BarChart3: "BarChart3",
  Settings: "Settings",
  ClipboardList: "ClipboardList",
  MessageSquare: "MessageSquare",
  Package: "Package",
  Megaphone: "Megaphone",
  Share2: "Share2",
  Layers: "Layers",
  Image: "Image",
  PieChart: "PieChart",
  Search: "Search",
  FileSearch: "FileSearch",
  Tag: "Tag",
  MapIcon: "MapIcon",
  MapPin: "MapPin",
  LayoutDashboard: "LayoutDashboard",
  FileText: "FileText",
  PenTool: "PenTool",
  Film: "Film",
  Linkedin: "Linkedin",
  Instagram: "Instagram",
  Youtube: "Youtube",
  CreditCard: "CreditCard",
  Receipt: "Receipt",
  Landmark: "Landmark",
  ScrollText: "ScrollText",
  Shield: "Shield",
  Key: "Key",
  AlertTriangle: "AlertTriangle",
  Send: "Send",
  AlertCircle: "AlertCircle",
  Palette: "Palette",
  Wallet: "Wallet",
  UserCheck: "UserCheck",
  Crosshair: "Crosshair",
  CheckSquare: "CheckSquare",
  Swords: "Swords",
  FileEdit: "FileEdit",
  LineChart: "LineChart",
  HeartPulse: "HeartPulse",
  Briefcase: "Briefcase",
  Building2: "Building2",
  BadgeCheck: "BadgeCheck",
  IndianRupee: "IndianRupee",
  Mail: "Mail",
  FolderOpen: "FolderOpen",
  CalendarOff: "CalendarOff",
  PartyPopper: "PartyPopper",
  MessageCircle: "MessageCircle",
  Code: "Code",
};

export function getModuleBySlug(slug: string) {
  return MODULE_REGISTRY.find((m) => m.slug === slug);
}

export function getChildrenByParentSlug(parentSlug: string) {
  return MODULE_REGISTRY.filter((m) => m.parent_slug === parentSlug).sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
}

export function buildBreadcrumbFromPath(pathSegments: string[]) {
  const breadcrumbs = [{ label: "APEX OS", href: "/" }];

  let currentPath = "/m";
  for (const segment of pathSegments) {
    currentPath += `/${segment}`;
    const mod = MODULE_REGISTRY.find((m) => m.path === currentPath);
    breadcrumbs.push({
      label: mod?.name || segment,
      href: currentPath,
    });
  }

  return breadcrumbs;
}
